### ISSUE TITLE
Invalid empty strings for host resource attributes in fqdn absent configuration

### ISSUE THREAD

**Issue by mickferg** [ghoneycutt/puppet-module-hosts#23]
Host resource expects valid array and IP address for 'host_aliases' and 'ip' attributes respectively. As a result empty strings given to these attributes in an '$fqdn_entry_enabled == false' configuration result in parsing errors. Changing the empty strings to undef for these host attributes seems to be acceptable though

**Comment by ghoneycutt** [comment]
This has been solved in V2 of the module
