### ISSUE TITLE
Avoid purging of localhost if enable_ipv4_localhost = false ?

### ISSUE THREAD

**Issue by mnellemann** [ghoneycutt/puppet-module-hosts#25]
Hi,

I'm trying to maintain "127.0.0.1  hostname.domain  hostname  localhost" in my hosts file. If I let the module handle localhost, I can specify aliases (in Hiera), but not $::hostname or similar. If not, the line is purged by the module. 

Could you provide an option to leave localhost ?

**Comment by ghoneycutt** [comment]
I don't understand what you are trying to achieve. Can you provide a line that you would like to see that is currently not possible?

**Comment by mnellemann** [comment]
Hi, 

Yes, sure :)

I want the following line in /etc/hosts, where myserver is $::hostname and mydomain is defined somewhere:

    127.0.0.1  myserver.mydomain  myserver   localhost

This line get's either purged or changed to:

    127.0.0.1	localhost.localdomain	localhost localhost4 localhost4.localdomain4

Does it make sense?

**Comment by lazyfrosch** [comment]
What Debian does per default is:

```
127.0.0.1   localhost
127.0.1.1   myhostname.mydomain myhostname
```

This works, but can cause problems when services are explicitly binding to `127.0.0.1`.

It is not really recommended to use 127.0.0.1 for the real hostname.

**Comment by mnellemann** [comment]
Hi,

This makes perfect sense - thanks.
