### ISSUE TITLE
How to keep hosts IP/fqdn from being deleted when purge_hosts is true?

### ISSUE THREAD

**Issue by claflico** [ghoneycutt/puppet-module-hosts#32]
Sorry to ask but I can't figure out how to make it work to where a hosts IP address and fqdn is not deleted when purge_hosts is true. 

I have 3 hosts specified via hiera in hosts::host_entries. I'm not using puppetdb or mysql or the like for my puppet master backend. 

I've tried every variation of enable_fqdn_entry, use_fqdn, fqdn_host_aliases, & collect_all and they all remove the host entry from its own /etc/hosts file. 

If I'm reading this line right, does it delete the fqdn from the host_entries hash? https://github.com/ghoneycutt/puppet-module-hosts/blob/master/manifests/init.pp#L147

**Comment by claflico** [comment]
I was able to get all three hosts to stay in my /etc/hosts file by changing init.pp to:

    #@@host { $::fqdn:
    #  ensure       => $fqdn_ensure,
    #  host_aliases => $my_fqdn_host_aliases,
    #  ip           => $fqdn_ip,
    #}

    $host_entries_real = $host_entries
    #$host_entries_real = delete($host_entries,$::fqdn)

So if you don't mind could you share what the variables need to be in order to accomplish this without the commented out sections.

**Comment by janvonde** [comment]
@ghoneycutt any comment on this? I have the same problem in a vagrant box  currently...

**Comment by ghoneycutt** [comment]
I don't quite grasp what the desired behavior is. Please elaborate including any hiera data, parameters, and an example /etc/hosts file.

**Comment by ghoneycutt** [comment]
Thanks to everyone involved. I've been very hesitant to accept any changes to this module because bugs in /etc/hosts can have a critical impact to systems. In order to make changes, I'm working on adding functional testing through Vagrant which will be released in V3 of this module.

PR #65 is for V3

Collections will not be used in the new version of the module.
