### ISSUE TITLE
$::hostname appears as string with Puppetdb

### ISSUE THREAD

**Issue by raiblue** [ghoneycutt/puppet-module-hosts#33]
Hi,
I've been using this module for a long time with no problems. But when I deployed Puppetdb to my environment, a problem occured. Host alias of host turned into $::hostname (as string) like that:

192.168.1.1   myhost.mydomain.com       $::hostname
192.168.1.20 otherhost.mydomain.com   alias.mydomain.com

When I looked to Puppetdb, i can see that $::hostname fact is taken right from client, it is "myhost". But it seems that there is a problem somewhere. I also can not override it from hiera:

hosts::host_entries:
  'myhost.mydomain.com':
    ip: '192.168.1.1'
    host_aliases:
    - 'myhost'
  'otherhost.mydomain.com':
    ip: '192.168.1.20'
    host_aliases:
    - 'alias.mydomain.com'

Again, $::hostname appears in hosts file instead of "myhost". There is no problem in other host aliases. I'm not sure what is going on.

**Comment by raiblue** [comment]
As I realized now, this problem is not related to puppetdb. When i moved to puppetdb, i also changed some hieras which override the hostname fact in wrong way. I'm closing the issue. Thanks.

**Comment by ghoneycutt** [comment]
@raiblue Thanks for following up. If you think the error you made could easily be made by others, perhaps we should document it.
