### ISSUE TITLE
::ipaddress for fqdn entry

### ISSUE THREAD

**Issue by jjbc** [ghoneycutt/puppet-module-hosts#35]
Hi, 

In case there are two interfaces, fqdn entry is always associated to ::ipaddress facter, which is equivalent to eth0 IP. 
But we could be interesed in setting fqdn entry to the second interface IP. 

Is it possible to add a parameter for the fqdn ip?

Kind regards. 
Juan José Blanco

**Comment by ghoneycutt** [comment]
Sure, I would accept a pull request with that. The code currently just sets `$::ipaddress`, so making that a parameter that defaults to `$::ipaddress` would be fine.
