### ISSUE TITLE
Does not create fqdn resource

### ISSUE THREAD

**Issue by robert4man** [ghoneycutt/puppet-module-hosts#40]
It creates the ipv4 and ipv6 localhost entries, but it is not creating the fqdn entry. I suspect it has something to do with the resource collection, but I can't seem to figure it out.

**Comment by ghoneycutt** [comment]
Could you include the values for the attributes of the class that you are specifying along with the generated /etc/hosts? Also are you using the latest version? What platform are you on?

**Comment by ghoneycutt** [comment]
Yes it appears that PuppetDB is required.

You might be able to get around this with the following in Hiera.

``` yaml
---
hosts::use_fqdn: false
hosts::host_entries:
  %{::fqdn}:
    ip: %{::ipaddress}
    host_aliases:
      - %{::hostname}
```

**Comment by robert4man** [comment]
I tried that once in my attempt to work around the issue, but I believe the delete($host_entries,$::fqdn) was taking it back out again. I even forked it to try and work around the issue by removing the delete. Maybe I'll try that again. I'm wondering if it would make sense to not use an exported resource for fqdn if collect_all is false. The one would only need a puppetdb if collect_all is true which would be expected.

**Comment by ghoneycutt** [comment]
If you could get it to work with preserving the current functionality, I would be happy to merge it.

**Comment by robert4man** [comment]
OK, I tried, but travis doesn't like me.

**Comment by robert4man** [comment]
I think the current pull request #42 honors the previous logic, but will require updates to the init_spec. The currently commented blocks for exported resources would conditionally exist depending on the options selected. The current failure appears to be related to the fact that a host index for monkey.example.com exists with ensure => absent whereas the spec currently thinks it should not exist at all.

**Comment by robert4man** [comment]
OK, it's passing the new tests, but I had to remove Ruby 1.8.7 from Travis due to rake v11.1.0.

**Comment by mewald1** [comment]
Is this fixed now?

**Comment by robert4man** [comment]
From my perspective it is, but @ghoneycutt was working to fix the Ruby 1.8.7 issue before merging it.

**Comment by gothicx** [comment]
I've done this in order to have the fqdn in the hosts entry:

-  @@host { $::fqdn:
+  host { $::fqdn:

**Comment by mtomov** [comment]
+1 on the same problem when not using exported resources. Thanks for the module though!

**Comment by gearboxscott** [comment]
@ghoneycutt    Hi Garrett, I agree with @gothicx, if you remove the @@ in front of host this fixes the adding the fqdn of the host to the /etc/hosts file.   Is it possible for you to make that change and republish to the Puppet Forge?

**Comment by nmaludy** [comment]
+1

**Comment by jurim76** [comment]
Any news about the fix? Same problem for me

**Comment by ghoneycutt** [comment]
I'm hesitant to make any changes, because of the high costs of any new bugs. To fix that, I'm working on V3 of this module which will have functional testing with Vagrant and allow us to be sure that changes work as expected.

Also will be dropping support for Puppet 3, adding support for Puppet 5 and using native data types.

**Comment by nmaludy** [comment]
:frowning_face: We use puppet 3 in production because we're running RHEL with Satellite.

The latest version of Satellite/Foreman that is supported by Red Hat only supports puppet 3.x . This is also "bleeding edge" with regards to Red Hat. Not sure when they are planning on supporting puppet 4, let alone puppet 5.

**Comment by ghoneycutt** [comment]
Does the patch in PR #49 fix this for you? If so, I'll merge this into master and use that for the final release supporting Puppet 3.

**Comment by nmaludy** [comment]
@ghoneycutt Yes the following pacth in #49 worked for me https://github.com/fnoop/puppet-module-hosts/commit/fa4a697aac80bb9e1266f596e0a180942bf733dd

I did have to set `stored_configs => false` but it does work!
```
  class { '::hosts':
    stored_config         => false,
    purge_hosts           => false,
    enable_ipv4_localhost => true,
    enable_ipv6_localhost => true,
    enable_fqdn_entry     => true,
  }
```

**Comment by ghoneycutt** [comment]
Closing as we have simplified the module with v3.0.0
