### ISSUE TITLE
"enable ipv6 localhost" have duplicates

### ISSUE THREAD

**Issue by shresthassh** [ghoneycutt/puppet-module-hosts#44]
::1     localhost6.localdomain6 localhost6 localhost6.localdomain6

Above is the result when I override with boolean=true.
I would like it to be similar to ipv4 with "localhost.localdomain   localhost" and remove duplicate " localhost6.localdomain6"

127.0.0.1       localhost.localdomain   localhost localhost4 localhost4.localdomain4

**Comment by ghoneycutt** [comment]
Closing as we have simplified the module with v3.0.0
