### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by sgtstadanko** [ghoneycutt/puppet-module-hosts#50]
New to puppet and learning.

Where do i add new hosts so that they get applied to clients?
Also does collect_all actually collect and store the existing hosts entries on each server?

thanks

**Comment by ghoneycutt** [comment]
collect_all works with PuppetDB. Each node will export its hostname to PuppetDB and collect_all would import them all to your system. This would mean everytime you add/remove a node to the network, the /etc/hosts would be updated on the next puppet run.

If you want to add nodes you need to `include ::hosts` and supply the hosts in Hiera

https://github.com/ghoneycutt/puppet-module-hosts#hiera-example-of-host_entries

**Comment by sgtstadanko** [comment]
Thanks. Im using Foreman so no PuppetDB.  Ill see if there is a way to plug that in.

**Comment by sgtstadanko** [comment]
So i got puppetdb installed to collect. If i want to add a host to all nodes, which hiera yaml file do I need to insert the example code into to add a host?
