### ISSUE TITLE
enable_fqdn_entry not working

### ISSUE THREAD

**Issue by sgtstadanko** [ghoneycutt/puppet-module-hosts#52]
Hi,
the hosts module isn't generating the fqdn entry for the hosts its applied on anymore.  Not sure what happened.  Its also not populating the other clients to the hosts file that its collected. 

I have tried deleting module, unassociating and reinstalling and still same results.

Any ideas or what to check?

Thanks.

**Comment by jordigg** [comment]
Duplicated from #40, I did send a PR #48 but is having problems with the tests.
