### ISSUE TITLE
v3 no longer creating default host entries as expected when using 'include ::hosts' with no data

### ISSUE THREAD

**Issue by ulysses-31** [ghoneycutt/puppet-module-hosts#75]
Previous 2.x versions you were able to keep the host fqdn entry in /etc/hosts up-to-date by just including the 'hosts' module (with no associated data defined for the hosts module). 
I have noticed the following two issues:

(1) With v3 of the hosts module the local fqdn entry is still managed however it is no longer idempotent resulting in an additional duplicate host entry being added each time puppet is run.

e.g. /etc/hosts after multiple puppet runs
10.3.4.148  testserver.mydomain.local      testserver
10.3.4.148  testserver.mydomain.local      testserver
10.3.4.148  testserver.mydomain.local      testserver

(2) v3 no longer ensures these default localhost entries are created in /etc/hosts:

127.0.0.1       localhost.localdomain   localhost localhost4 localhost4.localdomain4
::1     localhost6.localdomain6 localhost6 localhost6.localdomain6

**Comment by ghoneycutt** [comment]
Can you please provide an example manifest so I can re-create the issues.

**Comment by ulysses-31** [comment]
Hi. My directory environment only includes stdlib v4.25.1 and hosts v3 modules. I am able to reproduce with this simple manifest with puppet v4.10.9:

include ::hosts

**Comment by ghoneycutt** [comment]
Thanks for pointing this out! Added acceptance tests which also catch this at https://github.com/ghoneycutt/puppet-module-hosts/pull/65/commits/03d05f56b5139407557e69149b5819c303ae9f62#diff-8793845accebc0de146174b602f0afccR13

**Comment by ghoneycutt** [comment]
Closing as we have simplified the module with v3.0.0
