### ISSUE TITLE
problem with dual-stack IP

### ISSUE THREAD

**Issue by maxadamo** [ghoneycutt/puppet-module-hosts#77]
I didn't try this module, but from the code I see an issue with multiple IPs. 
Solving the issue is fairly easy: `hostname` should not be the resource name, but one of the parameters, otherwise you can't set the same host multiple times (like in the case of IPv4 and IPv6). 

You can take this link as an example (it's a module made 5 years ago): [uol/host6](https://forge.puppet.com/uol/host6)  
For instance, using that module I have the following: 
```
    'blahblah':
      ip           => 192.168.0.10,
      hostname     => 'myfqdn',
      host_aliases => 'myfqdn.domain';
    'blahblah-v6':
      ip           => '2001::.....',
      hostname     => 'myfqdn',
      host_aliases => 'myfqdn.domain';
```

**As you can see, I can use the same hostname twice** 

p.s.: I'd also implement some check against the datatype: `Stdlib::IP::Address`

**Comment by ghoneycutt** [comment]
Closing as we have simplified the module with v3.0.0
