### ISSUE TITLE
how can I extend module to maintain 2 or more hosts files

### ISSUE THREAD

**Issue by thiema** [ghoneycutt/puppet-module-hosts#78]
I have requirement to maintain 2 hosts files:
/etc/hosts and
/chroot/etc/hosts

Both hosts files may have different entries.

From my "unskilled" point of view it should be possible to somehow bring the target parameter which right now belongs to hosts one level down to hosts::host_entries.
The host resource type which is used does support for each entry, isnt it ?

**Comment by ghoneycutt** [comment]
You can now with v3.0.0
