### ISSUE TITLE
v3.0.0 is available on the Forge, but looks to be WIP...

### ISSUE THREAD

**Issue by redst011** [ghoneycutt/puppet-module-hosts#91]
I just noticed that v3.0.0 of the module was no longer acting the way it should...  Extra entries weren't being purged, for example.  Upon looking at the code, I realized that init.pp was almost entirely gutted, and I found another spot where it made it seem it should have been v2.8.0 that was released instead of v3.0.0.

Can anyone confirm whether or not v3.0.0 was the intended release?

**Comment by ghoneycutt** [comment]
It should be the intended release. Please check out the new v4.0.0. Changes were just to supported platforms and versions of Puppet.
